package DPSSCorba;


/**
* DPSSCorba/DPSSInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DPSSCorba.idl
* Saturday, June 20, 2020 7:59:49 o'clock PM EDT
*/

public interface DPSSInterface extends DPSSInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DPSSInterface
