package DPSSCorba;


/**
* DPSSCorba/DPSSInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DPSSCorba.idl
* Saturday, June 20, 2020 7:59:49 o'clock PM EDT
*/

abstract public class DPSSInterfaceHelper
{
  private static String  _id = "IDL:DPSSCorba/DPSSInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, DPSSCorba.DPSSInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DPSSCorba.DPSSInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DPSSCorba.DPSSInterfaceHelper.id (), "DPSSInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DPSSCorba.DPSSInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DPSSInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DPSSCorba.DPSSInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DPSSCorba.DPSSInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DPSSCorba.DPSSInterface)
      return (DPSSCorba.DPSSInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DPSSCorba._DPSSInterfaceStub stub = new DPSSCorba._DPSSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DPSSCorba.DPSSInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DPSSCorba.DPSSInterface)
      return (DPSSCorba.DPSSInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DPSSCorba._DPSSInterfaceStub stub = new DPSSCorba._DPSSInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
