package DPSSCorba;


/**
* DPSSCorba/DPSSInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DPSSCorba.idl
* Saturday, June 20, 2020 7:59:49 o'clock PM EDT
*/

public interface DPSSInterfaceOperations 
{

  // AdminInterface corba idl methods
  String getPlayerStatus (String userName, String password, String ipAddress);
  String suspendAccount (String AdminUsername, String AdminPassword, String AdminIP, String UsernameToSuspend);

  // PlayerInterface corba idl methods
  String createPlayerAccount (String firstName, String lastName, String age, String userName, String password, String ipAddress);
  String playerSignIn (String userName, String password, String ipAddress);
  String playerSignOut (String userName, String ipAddress);
  String transferAccount (String userName, String password, String OldIPAddress, String NewIPAddress);
} // interface DPSSInterfaceOperations
