package FECorba;


/**
* FECorba/FrontendInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FECorba.idl
* Saturday, July 25, 2020 3:53:10 o'clock PM EDT
*/

abstract public class FrontendInterfaceHelper
{
  private static String  _id = "IDL:FECorba/FrontendInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, FECorba.FrontendInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FECorba.FrontendInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FECorba.FrontendInterfaceHelper.id (), "FrontendInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FECorba.FrontendInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FrontendInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FECorba.FrontendInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FECorba.FrontendInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FECorba.FrontendInterface)
      return (FECorba.FrontendInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FECorba._FrontendInterfaceStub stub = new FECorba._FrontendInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FECorba.FrontendInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FECorba.FrontendInterface)
      return (FECorba.FrontendInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FECorba._FrontendInterfaceStub stub = new FECorba._FrontendInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
