package FECorba;


/**
* FECorba/FrontendInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FECorba.idl
* Saturday, July 25, 2020 3:53:10 o'clock PM EDT
*/

public interface FrontendInterfaceOperations 
{

  // AdminInterface corba idl methods
  String getPlayerStatus (String userName, String password, String ipAddress);
  String suspendAccount (String AdminUsername, String AdminPassword, String AdminIP, String UsernameToSuspend);

  // PlayerInterface corba idl methods
  String createPlayerAccount (String firstName, String lastName, String age, String userName, String password, String ipAddress);
  String playerSignIn (String userName, String password, String ipAddress);
  String playerSignOut (String userName, String ipAddress);
  String transferAccount (String userName, String password, String OldIPAddress, String NewIPAddress);
} // interface FrontendInterfaceOperations
