package FECorba;

/**
* FECorba/FrontendInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FECorba.idl
* Saturday, July 25, 2020 3:53:10 o'clock PM EDT
*/

public final class FrontendInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public FECorba.FrontendInterface value = null;

  public FrontendInterfaceHolder ()
  {
  }

  public FrontendInterfaceHolder (FECorba.FrontendInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FECorba.FrontendInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FECorba.FrontendInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FECorba.FrontendInterfaceHelper.type ();
  }

}
