package FECorba;


/**
* FECorba/FrontendInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FECorba.idl
* Saturday, July 25, 2020 3:53:10 o'clock PM EDT
*/

public interface FrontendInterface extends FrontendInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontendInterface
